### ISSUE TITLE
TRADES and MART Support

### ISSUE THREAD

**Issue by AlgebraLoveme** [TrustMLRG/EDAC#1]
Dear authors,

Congratulations on your new work! In your paper, Table 1 clearly states that TRADES+EDAC and MART+EDAC is always better than PGD+EDAC. However, I cannot find TRADES and MART component in the code released. In addition, the released models do not contain these as well. Could you please also share these codes and models?

Best

**Comment by minxingzhang** [comment]
Hi,

thanks for your interest.
We have uploaded the codes of TRADES-EDAC and MART-EDAC, which are based on the implementations of [TRADES](https://github.com/yaodongyu/TRADES) and [MART](https://github.com/YisenWang/MART/tree/master).

Best,
Minxing

**Comment by AlgebraLoveme** [comment]
Thanks!
